#!/usr/bin/env python3
"""Extract embedded skill/workflow prompts from the Claude Code binary.

The binary ships built-in skills (code-review, verify, simplify, ...) and
workflows (code-review ultra, deep-research) as JS template literals. The
inter-version diff of these prompts is an unpublished vendor changelog.

Output: research/binary-extracts/<version>.md — one block per extracted
prompt region, content-keyed (marker phrase), normalized, sorted. Idempotent:
same binary → identical file. Diff versions with plain `git diff` or
`just binary-skills-diff`.

Provenance: research/2026-06-12-vendor-binary-skill-archaeology.md
"""

import hashlib
import re
import sys
from pathlib import Path

# Stable content markers — phrases that anchor known prompt families across
# versions. Add markers when new built-ins appear; removal of a marker's block
# from the output IS the signal that the vendor dropped/renamed the prompt.
MARKERS = [
    b"Review the current diff for correctness bugs",
    b"You are reviewing for **recall**",
    b"You are reviewing for **precision**",
    b"REFUTED** only when constructible from the code",
    b"Phase 2 \\u2014 Verify",
    b"Phase 3 \\u2014 Sweep for gaps",
    b"Verification is runtime observation",
    b"The verdict is table stakes",
    b"diagnose frozen/slow Claude Code sessions",
    b"Constructing a Hook (with verification)",
    b"// code-review: Scope",
    b"// deep-research: Scope",
    b"Adversarial Claim Verifier",
    b"cleanup agents in parallel",
]

CONTEXT_BEFORE = 2_000
CONTEXT_AFTER = 12_000


def printable_window(data: bytes, start: int, end: int) -> str:
    chunk = data[max(0, start) : min(len(data), end)]
    text = chunk.decode("utf-8", "replace")
    # Trim to whole lines and strip the JS-minification noise at the edges.
    lines = text.splitlines()
    return "\n".join(lines[1:-1]) if len(lines) > 2 else text


def main() -> int:
    binary = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / ".local/bin/claude"
    binary = binary.resolve()
    version = binary.name  # versions/<X.Y.Z>
    data = binary.read_bytes()

    out_dir = Path(__file__).resolve().parent.parent / "research" / "binary-extracts"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{version}.md"

    blocks: list[tuple[str, str]] = []
    missing: list[str] = []
    for marker in MARKERS:
        positions = [m.start() for m in re.finditer(re.escape(marker), data)]
        if not positions:
            missing.append(marker.decode())
            continue
        # First occurrence is canonical; duplicates are minifier re-emissions.
        pos = positions[0]
        body = printable_window(data, pos - CONTEXT_BEFORE, pos + CONTEXT_AFTER)
        digest = hashlib.sha256(body.encode()).hexdigest()[:12]
        blocks.append((marker.decode(), f"<!-- sha:{digest} hits:{len(positions)} -->\n{body}"))

    blocks.sort(key=lambda b: b[0])
    parts = [
        f"# Claude Code {version} — embedded prompt extraction\n",
        f"Binary: `{binary}` ({len(data):,} bytes). Generated by `scripts/binary_skills_extract.py`.\n",
    ]
    if missing:
        parts.append("## MISSING MARKERS (vendor dropped/renamed — investigate)\n"
                      + "\n".join(f"- `{m}`" for m in missing) + "\n")
    for name, body in blocks:
        parts.append(f"\n---\n\n## marker: `{name}`\n\n```\n{body}\n```\n")
    out_path.write_text("".join(parts))
    print(f"✓ {out_path} — {len(blocks)} blocks, {len(missing)} missing markers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
