"""Shared config for codebase-map refresh (commit hook, launchd, batch)."""
from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "config" / "codebase-map-repos.json"

# Generated map outputs — must stay out of git (regenerated by refresh-maps / hooks).
MAP_GITIGNORE_DEFAULT = (
    ".claude/rules/codebase-map.md",
    ".claude/maps/",
)


@dataclass(frozen=True)
class RepoMapConfig:
    name: str
    root: Path
    source_dirs: tuple[str, ...]
    compact: bool = False
    extra_gitignore: tuple[str, ...] = field(default_factory=tuple)


def gitignore_patterns(cfg: RepoMapConfig) -> tuple[str, ...]:
    return MAP_GITIGNORE_DEFAULT + cfg.extra_gitignore


def load_repo_configs(path: Path = CONFIG_PATH) -> dict[str, RepoMapConfig]:
    raw = json.loads(path.read_text())
    out: dict[str, RepoMapConfig] = {}
    for name, cfg in raw.get("repos", {}).items():
        root = Path(cfg.get("root", f"~/Projects/{name}")).expanduser().resolve()
        out[name] = RepoMapConfig(
            name=name,
            root=root,
            source_dirs=tuple(cfg["source_dirs"]),
            compact=bool(cfg.get("compact")),
            extra_gitignore=tuple(cfg.get("extra_gitignore", ())),
        )
    return out


def config_for_repo(repo_root: Path, configs: dict[str, RepoMapConfig] | None = None) -> RepoMapConfig | None:
    configs = configs or load_repo_configs()
    resolved = repo_root.resolve()
    for cfg in configs.values():
        if cfg.root == resolved:
            return cfg
    return configs.get(resolved.name)


def assert_maps_gitignored(cfg: RepoMapConfig) -> None:
    """Refuse to write generated maps unless outputs are gitignored and untracked."""
    issues: list[str] = []
    gitignore = cfg.root / ".gitignore"
    if not gitignore.exists():
        issues.append("missing .gitignore")
    else:
        text = gitignore.read_text()
        for pattern in gitignore_patterns(cfg):
            if pattern not in text:
                issues.append(f".gitignore missing `{pattern}`")

    try:
        tracked = subprocess.check_output(
            ["git", "-C", str(cfg.root), "ls-files", "--", ".claude/maps/"],
            text=True,
        ).strip()
        if tracked:
            issues.append(
                f"tracked map detail files ({len(tracked.splitlines())}) — "
                "run: git rm -r --cached .claude/maps/"
            )
        for path in (".claude/rules/codebase-map.md", *cfg.extra_gitignore):
            if (
                subprocess.run(
                    ["git", "-C", str(cfg.root), "ls-files", "--error-unmatch", path],
                    capture_output=True,
                ).returncode
                == 0
            ):
                issues.append(f"`{path}` is tracked — run: git rm --cached {path}")
    except (subprocess.CalledProcessError, OSError) as exc:
        issues.append(f"git ls-files failed: {exc}")

    if issues:
        raise RuntimeError(
            f"{cfg.name}: generated codebase maps must be gitignored — "
            + "; ".join(issues)
        )
