#!/usr/bin/env python3
"""Harness changelog — track measured outcomes of harness file changes.

Scans git log for commits touching harness files (CLAUDE.md, rules/, settings.json).
For each change, records the commit, files changed, and quality scores from sessions
before and after the change. Outputs to harness-changelog.md (append-only).

Usage:
    harness-changelog.py [--days N] [--output FILE]

Evidence: Meta-Harness (Lee et al. 2026, arXiv:2603.28052) — scored iteration
over harness variants is the core methodology. This is the lightweight version.
"""

import argparse
import json
import sqlite3
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from common.paths import SESSIONS_DB


# Harness files — commits touching these are harness changes
HARNESS_PATTERNS = [
    "CLAUDE.md",
    ".claude/rules/",
    ".claude/settings.json",
    "scripts/hooks/",
]

# Also check global harness files (in skills repo, home dir)
GLOBAL_PATTERNS = [
    "hooks/",  # in skills repo
]


def find_harness_commits(days: int = 30, repo: str = ".") -> list[dict]:
    """Find commits that touch harness files in the last N days."""
    since = f"--since={days} days ago"
    result = subprocess.run(
        ["git", "-C", repo, "log", "--oneline", "--name-only", since, "--format=%H|%s|%ai"],
        capture_output=True, text=True, timeout=10,
    )
    if result.returncode != 0:
        return []

    commits = []
    current = None
    for line in result.stdout.strip().split("\n"):
        if not line:
            continue
        if "|" in line and len(line.split("|")[0]) == 40:
            parts = line.split("|", 2)
            current = {"hash": parts[0], "subject": parts[1], "date": parts[2].strip(), "files": []}
            commits.append(current)
        elif current is not None:
            current["files"].append(line.strip())

    # Filter to harness-touching commits
    harness_commits = []
    for c in commits:
        harness_files = [
            f for f in c["files"]
            if any(p in f for p in HARNESS_PATTERNS)
        ]
        if harness_files:
            c["harness_files"] = harness_files
            harness_commits.append(c)

    return harness_commits


def get_quality_around(db: sqlite3.Connection, date_str: str, window: int = 10) -> dict:
    """Get quality scores for sessions before and after a date."""
    # Parse date (git format: 2026-04-07 10:30:00 -0500)
    date_prefix = date_str[:19]  # YYYY-MM-DD HH:MM:SS

    before = db.execute("""
        SELECT ROUND(AVG(sq.quality_score), 3) as avg_q, COUNT(*) as n
        FROM sessions s
        JOIN session_quality sq ON s.uuid = sq.uuid
        WHERE s.start_ts < ?
        ORDER BY s.start_ts DESC
        LIMIT ?
    """, [date_prefix, window]).fetchone()

    after = db.execute("""
        SELECT ROUND(AVG(sq.quality_score), 3) as avg_q, COUNT(*) as n
        FROM sessions s
        JOIN session_quality sq ON s.uuid = sq.uuid
        WHERE s.start_ts > ?
        ORDER BY s.start_ts ASC
        LIMIT ?
    """, [date_prefix, window]).fetchone()

    return {
        "before_avg": before["avg_q"] if before and before["n"] >= 3 else None,
        "before_n": before["n"] if before else 0,
        "after_avg": after["avg_q"] if after and after["n"] >= 3 else None,
        "after_n": after["n"] if after else 0,
    }


def main():
    parser = argparse.ArgumentParser(description="Harness changelog with quality scores")
    parser.add_argument("--days", type=int, default=30, help="Look back N days (default: 30)")
    parser.add_argument("--output", "-o", default="harness-changelog.md", help="Output file")
    args = parser.parse_args()

    commits = find_harness_commits(args.days)
    if not commits:
        print("No harness commits found.", file=sys.stderr)
        return

    db = sqlite3.connect(SESSIONS_DB)
    db.row_factory = sqlite3.Row

    # Check if session_quality table exists
    tables = {r[0] for r in db.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()}
    has_quality = "session_quality" in tables

    output_path = Path(args.output)
    lines = []

    if not output_path.exists():
        lines.append("# Harness Changelog")
        lines.append("")
        lines.append("Tracked changes to harness files (CLAUDE.md, rules/, hooks, settings.json)")
        lines.append("with before/after session quality scores.")
        lines.append("")
        lines.append("Generated by `harness-changelog.py`. Evidence: Meta-Harness (arXiv:2603.28052).")
        lines.append("")

    # Read existing to avoid duplicates
    existing_hashes = set()
    if output_path.exists():
        for line in output_path.read_text().split("\n"):
            if line.startswith("### ") and "[" in line:
                # Extract hash from ### YYYY-MM-DD [abc1234]
                parts = line.split("[")
                if len(parts) >= 2:
                    h = parts[1].split("]")[0]
                    existing_hashes.add(h)

    new_entries = 0
    for c in reversed(commits):  # chronological order
        short_hash = c["hash"][:7]
        if short_hash in existing_hashes:
            continue

        date = c["date"][:10]
        files_str = ", ".join(c["harness_files"])

        entry = f"### {date} [{short_hash}] {files_str} — {c['subject']}"
        lines.append(entry)

        if has_quality:
            q = get_quality_around(db, c["date"])
            if q["before_avg"] is not None and q["after_avg"] is not None:
                delta = q["after_avg"] - q["before_avg"]
                sign = "+" if delta >= 0 else ""
                lines.append(f"- Before ({q['before_n']} sessions): avg quality {q['before_avg']}")
                lines.append(f"- After ({q['after_n']} sessions): avg quality {q['after_avg']}")
                lines.append(f"- Delta: {sign}{delta:.3f}")
            elif q["before_avg"] is not None:
                lines.append(f"- Before ({q['before_n']} sessions): avg quality {q['before_avg']}")
                lines.append(f"- After: insufficient data ({q['after_n']} sessions)")
            else:
                lines.append("- Quality data: insufficient sessions for comparison")
        else:
            lines.append("- Quality data: run `session-features.py --enrich-db` first")

        lines.append("")
        new_entries += 1

    db.close()

    if new_entries == 0:
        print("No new harness commits to add.", file=sys.stderr)
        return

    # Append to file
    with open(output_path, "a") as f:
        f.write("\n".join(lines))
        if lines:
            f.write("\n")

    print(f"Added {new_entries} entries to {output_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
